### ISSUE TITLE
Add description and URL to GH pages

### ISSUE THREAD

**Issue by jethrogb** [Manishearth/rust-internals-docs#1]
I can never find the this repository when searching on Google and even then figuring out the correct GH pages URL is cumbersome. I don't think I can file a PR that would result in the creation of a new branch on this repository so instead I suggest you copy this branch: https://github.com/jethrogb/rust-internals-docs/tree/master

**Comment by Manishearth** [comment]
I don't want to add extra things to the repo itself, but I modified the description at the top of the github repo main page with your text. Thanks!

**Comment by jethrogb** [comment]
That works, thanks!
